# Generated by Django 2.1.2 on 2018-10-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_deductions_earnings_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
